### ISSUE TITLE
Asciidoc conversion does not respect heading levels

### ISSUE THREAD

**Issue by lewtun** [fastai/fastdoc#11]
Hi @jph00,

First of all, thank you for open-sourcing this tool - it's super useful for a textbook I'm currently working on! 

I'm running into a small problem with the heading levels. Please see the details below. 

### Description of the problem

I have a notebook with different heading levels (simple gist [here](https://gist.github.com/lewtun/9ad150402532c937d3e347ed9e5fba25)) all of which appear with the _same_ `==` level in the resulting `.asciidoc` file.

Is this by design or does one need to add a special flag to the markdown cells?

### Steps to reproduce

1. Download the simple notebook from [this gist](https://gist.github.com/lewtun/9ad150402532c937d3e347ed9e5fba25)
2. Run the following commands
```bash
cd path/to/fastdoc_sections_test.ipynb
mkdir images
fastdoc_convert_all --path ./ --dest_path convert_book
```

### Expected output
An `fastdoc_sections_test.asciidoc` file with the following content
```
== Heading level 1

=== Heading level 2

==== Heading level 3
```

### Actual output
```
== Heading level 1

== Heading level 2

== Heading level 3
```

**Comment by lewtun** [comment]
Sorry, just saw this is a duplicate of #10. Closing the issue

**Comment by jph00** [comment]
Well spotted :D
