### ISSUE TITLE
table conversion doesn't work

### ISSUE THREAD

**Issue by deep-diver** [fastai/fastdoc#2]
I have tested out converting `fastbook` into asciidoc and pdf using `asciidoctor` and `asciidoctor-pdf`.
everything looks nicely rendered except for table. it seems like table rendering shows raw `HTML` tags.

I attach an example screenshot. (from chapter 10)

<img width="1085" alt="Screen Shot 2020-10-13 at 2 42 46 PM" src="https://user-images.githubusercontent.com/26025527/95819993-3a3d8b00-0d62-11eb-8ad4-b3466fe06149.png">

**Comment by deep-diver** [comment]
I think the only tables drawn by Pandas DataFrame doesnt properly rendered.

**Comment by sgaseretto** [comment]
Is there any solution to this?
