### ISSUE TITLE
conda installation channel

### ISSUE THREAD

**Issue by robintibor** [fastai/fastdoc#4]
Was wondering if  it should really be 
`conda install fastdoc`
or if it should be
` conda install -c fastai fastdoc`
as also here: https://anaconda.org/fastai/fastdoc

**Comment by kilianovski** [comment]
The first option didn't work for me:

```
PackagesNotFoundError: The following packages are not available from current channels:                                                                                                                                                            - fastdoc       
```

So I installed using pip. Maybe, it is better to have `conda install -c fastai fastdoc` in readme.

**Comment by AllenDowney** [comment]
When I installed using conda, I did not get `jupyter_contrib_nbextensions`
I ran

```
conda install -c conda-forge jupyter_contrib_nbextensions
```

which solved the problem.
