### ISSUE TITLE
Should some errors be warnings?

### ISSUE THREAD

**Issue by AllenDowney** [fastai/fastdoc#8]
On my first pass through my notebooks, I am seeing two errors:

* `Found a non-processed block quote, please fix`

* `Found code too long in a cell`

Both are errors, so they cause the conversion to stop.  Could these be warnings?  I would like to convert these documents anyway, and clean up these issues later.

**Comment by jph00** [comment]
Sorry about the delay on this - didn't see your request. It's a good idea to at-mention me since this repo isn't very active yet, so I'm not looking at it very regularly.

**Comment by AllenDowney** [comment]
@jph00 Got it.  Will do on future issues.
